server:
  port: 8083
  servlet:
    context-path: /activity-connector

spring:
  application:
    name: activity_connector

github:
  baseUrl: https://api.github.com
  repository-path: ${github.baseUrl}/users/%s/repos
  commit-path: ${github.baseUrl}/repos/%s/%s/commits